import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * Generate a styled industrial PDF report from AI outputs.
 */
export function generatePdfReport(content: string, type: string) {
  const doc = new jsPDF({ format: 'a4', unit: 'mm' });
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Clean markdown syntax but keep some structure
  let cleanTxt = content.replace(/\*\*/g, '').replace(/`/g, '');
  
  // --- Header ---
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, pageWidth, 35, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('NORTH SEA PLATFORM ALPHA (NPA)', 14, 15);
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`OPERATIONS DOCUMENTATION — FOR INTERNAL USE ONLY`, 14, 23);
  doc.text(`REPORT TYPE: ${type.toUpperCase().replace('_', ' ')}`, 14, 29);
  
  doc.setFontSize(9);
  doc.text(`ISSUE DATE: ${new Date().toISOString().substring(0, 10)}`, pageWidth - 55, 15);
  doc.text(`REF ID: NPA-OPS-${Date.now().toString().slice(-6)}`, pageWidth - 55, 21);
  doc.text(`SYSTEM: GENERATED BY STATEFUL AI`, pageWidth - 55, 27);

  // --- Body ---
  doc.setTextColor(30, 41, 59);
  
  let currentY = 45;

  // Function to add a section header
  const addSection = (title: string, y: number) => {
    doc.setFillColor(241, 245, 249);
    doc.rect(14, y - 5, pageWidth - 28, 8, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(71, 85, 105);
    doc.text(title.toUpperCase(), 16, y);
    doc.setTextColor(30, 41, 59);
    return y + 10;
  };

  if (cleanTxt.includes('[WORK ORDER DRAFT]')) {
    cleanTxt = cleanTxt.replace(/\[WORK ORDER DRAFT\]\n/g, '');
    currentY = addSection('Maintenance Work Order', currentY);
    
    const lines = cleanTxt.split('\n').filter(l => l.trim() !== '' && !l.startsWith('---'));
    const tableData: any[] = [];
    let remainingText = '';
    
    lines.forEach(line => {
      const splitMatches = line.match(/^([A-Za-z_ \/]+):\s*(.*)$/);
      if (splitMatches && splitMatches.length === 3) {
        tableData.push([splitMatches[1].trim(), splitMatches[2].trim()]);
      } else {
        remainingText += line + '\n';
      }
    });

    if (tableData.length > 0) {
      autoTable(doc, {
        startY: currentY,
        body: tableData,
        theme: 'grid',
        styles: { fontSize: 10, cellPadding: 3, font: 'helvetica' },
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50, fillColor: [248, 250, 252] } },
      });
      currentY = (doc as any).lastAutoTable.finalY + 12;
    }

    if (remainingText.trim() !== '') {
      currentY = addSection('Task Description & Safety Protocols', currentY);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      const splitText = doc.splitTextToSize(remainingText.trim(), pageWidth - 28);
      doc.text(splitText, 14, currentY);
    }
  } else {
    // Process generic reports (Anomaly, Safety Brief) using headings if present
    const topLevelLines = cleanTxt.split('\n');
    let hasDrawn = false;

    topLevelLines.forEach(line => {
      const headingMatch = line.match(/^- ([A-Z ]+):\s*(.*)$/);
      if (headingMatch) {
         currentY = addSection(headingMatch[1], currentY);
         doc.setFont('helvetica', 'normal');
         doc.setFontSize(10);
         const splitText = doc.splitTextToSize(headingMatch[2], pageWidth - 28);
         doc.text(splitText, 14, currentY);
         currentY += (splitText.length * 5) + 5;
         hasDrawn = true;
      }
    });

    if (!hasDrawn) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(11);
      const splitText = doc.splitTextToSize(cleanTxt, pageWidth - 28);
      doc.text(splitText, 14, 45);
    }
  }

  // --- Footer ---
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text('CONFIDENTIAL - NPA INTERNAL USE ONLY', 14, pageHeight - 10);
  doc.text('Generated by Stateful Operations Agent', pageWidth - 70, pageHeight - 10);
  
  doc.save(`NPA_${type.replace(/\s+/g, '_')}_${Date.now()}.pdf`);
}
