import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * Generate a styled industrial PDF report from AI outputs.
 */
export function generatePdfReport(content: string, type: string) {
  const doc = new jsPDF({ format: 'a4', unit: 'mm' });
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Clean markdown syntax
  let cleanTxt = content.replace(/\*\*/g, '').replace(/`/g, '');
  
  // --- Header ---
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, pageWidth, 28, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('NORTH SEA PLATFORM ALPHA (NPA)', 14, 12);
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`REPORT TYPE: ${type.toUpperCase()}`, 14, 20);
  
  doc.setFontSize(9);
  doc.text(`DATE: ${new Date().toISOString().substring(0, 10)}`, pageWidth - 40, 12);
  doc.text(`SECURE AI GENERATED`, pageWidth - 45, 20);

  // --- Body ---
  doc.setTextColor(30, 41, 59);
  
  // Extract key-value blocks (like [WORK ORDER DRAFT] lines)
  if (cleanTxt.includes('[WORK ORDER DRAFT]')) {
    cleanTxt = cleanTxt.replace(/\[WORK ORDER DRAFT\]\n/g, '');
    
    // Attempt to extract structured fields if any
    const lines = cleanTxt.split('\n').filter(l => l.trim() !== '');
    const tableData: any[] = [];
    let generalDesc = '';
    
    lines.forEach(line => {
      const splitMatches = line.match(/^([A-Za-z_ \/]+):\s*(.*)$/);
      if (splitMatches && splitMatches.length === 3) {
        tableData.push([splitMatches[1].trim(), splitMatches[2].trim()]);
      } else {
        generalDesc += line + '\n';
      }
    });

    if (tableData.length > 0) {
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('MAINTENANCE WORK ORDER', 14, 40);

      autoTable(doc, {
        startY: 45,
        body: tableData,
        theme: 'grid',
        headStyles: { fillColor: [51, 65, 85] },
        styles: { fontSize: 10, cellPadding: 3, font: 'helvetica' },
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50, fillColor: [248, 250, 252] } },
      });
      
      if (generalDesc.trim() !== '') {
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.text('NOTES / DESCRIPTION', 14, (doc as any).lastAutoTable.finalY + 15);
        
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        const splitText = doc.splitTextToSize(generalDesc.trim(), pageWidth - 30);
        doc.text(splitText, 14, (doc as any).lastAutoTable.finalY + 22);
      }
    } else {
      // Fallback
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(11);
      const splitText = doc.splitTextToSize(cleanTxt, pageWidth - 30);
      doc.text(splitText, 14, 40);
    }
  } else {
    // Standard text document (Anomaly Report, Safety Brief)
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    
    // Simple split
    const splitText = doc.splitTextToSize(cleanTxt, pageWidth - 30);
    doc.text(splitText, 14, 40);
  }

  // --- Footer ---
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text('CONFIDENTIAL - NPA INTERNAL USE ONLY', 14, pageHeight - 10);
  doc.text('Generated by Stateful Operations Agent', pageWidth - 70, pageHeight - 10);
  
  doc.save(`NPA_${type.replace(/\s+/g, '_')}_${Date.now()}.pdf`);
}
